name: 'Deploy to Replit'
description: 'Deploy your GitHub repo to Replit Deployments'
inputs:
  replId:
    description: 'The repl ID that this repo is linked to'
    required: true
  token:
    description: 'Your connect.sid token - this is only needed to pull the latest commit and deploy the Repl'
    required: true
  subdomain:
    description: 'The replit.app subdomain that your Repl will be hosted on.'
    required: true
  buildCommand:
    description: "The build command for your deployment to run."
    required: false
  runCommand: 
    description: "The command your deployment will run when it starts."
    required: true
outputs:
  deploymentId:
    description: 'The ID of the deployment'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'upload-cloud'
  color: 'white'